server:
  port: 8900

eureka:
  client:
    service-url:
      default-zone: http://127.0.0.1:8761/eureka/


spring:
  zipkin:
    base-url: http://localhost:9411/

  sleuth:
    sampler:
      probability: 1