server:
  port: 8080

spring:
  application:
    name: GatewayService

eureka:
  client:
    service-url:
      default-zone: http://127.0.0.1:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

zuul:
  routes:
    product:
      service-id: ProductService
    stock:
      service-id: StockService
      path: /stock/**