server:
  port: 8761

spring:
  application:
    name: EurekaServiceOne

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://127.0.0.1:8761/eureka/,http://127.0.0.1:8762/eureka/
#  instance:
#    hostname: server1

